#compile maven
language: java
sudo: false
script: mvn clean package

# deploy to github
deploy:
  provider: releases
  github_token: $GITHUB_TOKEN
  file: build/target/*.jar
  skip_cleanup: true
  on:
    tags: true
