#compile maven
language: java
sudo: false
script: mvn clean package

# deploy to github
deploy:
  provider: releases
  api-key: "9d9e674ab94bdd9865d23b560317a8df1827310d"
  file: build/target/*.jar
  skip_cleanup: true
  on:
    tags: true
