name: ${name}
description: ${description}
version: ${project.version}
main: me.christopherleemiller.PingListMOTD.PingListMOTD
api-version: 1.15

commands:
    pinglist:
        description: general command


permissions:
    pinglist.admin:
        description: all inclusive permission